# Generated by Django 2.1.7 on 2019-03-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='bio',
            new_name='interests',
        ),
    ]
