# Generated by Django 2.1.7 on 2019-03-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190321_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Teams',
        ),
    ]
